version: 2

project_name: nanoproxy

dist: dist

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: '{{ incpatch .Version }}-next'

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - id: nanoproxy
    binary: nanoproxy
    ldflags:
      - -s -w
      - -X nanoproxy.version={{.Version}}
      - -X nanoproxy.commit={{.Commit}}
      - -X nanoproxy.date={{ .CommitDate }}
      - -X nanoproxy.builtBy=goreleaser
      - -X nanoproxy.treeState={{ .IsGitDirty }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - '5'
      - '6'
      - '7'
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

changelog:
  use: git
  sort: asc
  groups:
    - title: "Dependency updates"
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
      order: 400
    - title: "Build process updates"
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 400
    - title: "Other work"
      order: 9999
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

archives:
  - id: default
    ids:
      - nanoproxy
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- .Arch }}_
      {{- .Arm }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

release:

  name_template: "{{ .Version }}"




